services:
  bot:
    logging:
      driver: syslog
      options:
        syslog-format: "rfc5424"
        syslog-address: "${LOGGING_URL}"
    container_name: doom-bot
    build: .
    environment:
      - TOKEN=${TOKEN}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_USER=${PSQL_USER}
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_DATABASE=${PSQL_DATABASE}
      - PSQL_PORT=${PSQL_PORT}
    networks:
      - doom-network

networks:
  doom-network:
    external: true
