services:
  bot:
    logging:
      driver: syslog
      options:
        syslog-format: "rfc5424"
        syslog-address: "${LOGGING_URL}"
    container_name: doom-bot
    env_file:
      - .env
    build: .
    environment:
      - TOKEN=${TOKEN}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_DATABASE=${PSQL_DATABASE}
      - PSQL_PORT=${PSQL_PORT}
    depends_on:
      - db
  db:
    container_name: doom-postgres
    env_file:
      - .env
    build: ./postgres/
    restart: unless-stopped
    ports:
      - "9889:5432"
    volumes:
      - "$HOME/doom-postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
#  grafana:
#    container_name: shimada-grafana
#    env_file:
#      - .env
#    image: grafana/grafana-enterprise
#    restart: unless-stopped
#    ports:
#      - '3000:3000'
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#    volumes:
#      - 'grafana_storage:/var/lib/grafana'
#volumes:
#  grafana_storage: { }