services:
  bot:
    logging:
      driver: syslog
      options:
        syslog-format: "rfc5424"
        syslog-address: "${LOGGING_URL}"
    build: .
    environment:
      - TOKEN=${TOKEN}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PYTHON_ENV=${PYTHON_ENV}
    depends_on:
      - db
  db:
    build: ./postgres/
    restart: unless-stopped
    ports:
      - "${PSQL_EXPOSE_PORT}:5432"
    volumes:
      - "$HOME/doom-postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
