name: doom-postgres

services:
  db:
    container_name: doom-postgres
    build: .
    restart: unless-stopped
    volumes:
      - "$HOME/doom-postgres/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
    networks:
      - doom-network

  dbgate:
    image: dbgate/dbgate
    restart: always
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: PSQL
      LABEL_PSQL: PostgreSQL - Doom
      SERVER_PSQL: db
      PASSWORD_MODE_PSQL: askUser
      PORT_PSQL: 5432
      ENGINE_PSQL: postgres@dbgate-plugin-postgres
    networks:
      - doom-network
      - contabo_network

  webdb:
      image: webdb/app
      restart: always
      volumes:
          - "$HOME/.webdb:/usr/src/app/static/version"
      environment:
        - SCAN_HOSTS=db
      networks:
        - doom-network
        - contabo_network


volumes:
  dbgate-data:
    driver: local

networks:
  doom-network:
    external: true
  contabo_network:
    external: true
