on:
  push: 
    branches:
    - development
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env: 
      TOKEN: ${{ env.TOKEN }}
      LOGGING_URL: ${{ env.LOGGING_URL }}
      PSQL_EXPOSE_PORT: ${{ env.PSQL_EXPOSE_PORT }}
      PSQL_PASSWORD: ${{ env.PSQL_PASSWORD }}
      PSQL_USER: ${{ env.PSQL_USER }}
      PYTHON_ENV: ${{ env.PYTHON_ENV }}
    steps:
    # need checkout before using docker-compose-remote-action
    - uses: actions/checkout@v2
    - uses: chaplyk/docker-compose-remote-action@v1.1
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_key: ${{ secrets.SSH_KEY }}
        compose_file: docker-compose.yml
        build: true
