on:
  push: 
    branches:
    - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2

    - uses: tylovejoy/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        
        docker_compose_prefix: doom-dev
